apps/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("users/list/", views.UserListView.as_view(), name="user_list"),
    path("users/create/", views.UserCreateView.as_view(), name="user_create"),
    path("users/<uuid:pk>/detail/", views.UserDetailView.as_view(), name="user_detail"),
    path("users/<uuid:pk>/update/", views.UserUpdateView.as_view(), name="user_update"),
    path("users/<uuid:pk>/delete/", views.UserDeleteView.as_view(), name="user_delete"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("", include("apps.users.urls")),
    path("", include("apps.programs.urls")),
    path("", include("apps.administrators.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/programs/models.py
from django.db import models
import uuid


class Program(models.Model):
    program_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=45)
    description = models.CharField(max_length=45)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

apps/users/models.py
from django.db import models
import re
import uuid
from django.core.exceptions import ValidationError
from apps.programs.models import Program


def validate_image_key(image_path):
    match = re.search(r"([^/]+)(?=\.[^.]+$)", image_path)
    return match.group(0) if match else None


def validate_image_size(image):
    MAX_SIZE = 5 * 1024 * 1024
    if image.size > MAX_SIZE:
        raise ValidationError("A imagem deve ter no máximo 5 MB.")


def validate_cpf(cpf):

    cpf = re.sub(r"[^0-9]", "", cpf)

    if len(cpf) != 11:
        raise ValidationError("CPF deve ter 11 dígitos.")

    if cpf == cpf[0] * len(cpf):
        raise ValidationError("CPF inválido.")

    def calcular_dv(cpf, peso):
        soma = sum(int(digito) * peso for digito, peso in zip(cpf, peso))
        resto = soma % 11
        if resto < 2:
            return 0
        return 11 - resto

    peso1 = list(range(10, 1, -1))
    dv1 = calcular_dv(cpf[:9], peso1)

    peso2 = list(range(11, 1, -1))
    dv2 = calcular_dv(cpf[:10], peso2)

    if int(cpf[9]) != dv1 or int(cpf[10]) != dv2:
        raise ValidationError("CPF inválido.")

    return cpf


class User(models.Model):
    user_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    username = models.CharField(max_length=100, verbose_name="Nome")
    document = models.CharField(
        unique=True,
        max_length=15,
        verbose_name="CPF",
        validators=[validate_cpf],
    )

    course = models.CharField(max_length=45, verbose_name="Curso")
    registration_code = models.CharField(
        unique=True, max_length=45, verbose_name="Código de Matrícula"
    )
    photo = models.ImageField(
        upload_to="user_photos/", validators=[validate_image_size], verbose_name="Foto"
    )
    key = models.CharField(
        unique=True, max_length=100, blank=True, verbose_name="Chave da Imagem"
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Criado em")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Atualizado em")
    program = models.ForeignKey(
        Program, on_delete=models.SET_NULL, null=True, related_name="users"
    )

    def save(self, *args, **kwargs):
        if self.photo and not self.key:
            self.key = validate_image_key(self.photo.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.username

apps/users/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import User
from ..administrators.models import Administrator
from ..programs.models import Program


class UserForm(forms.ModelForm):
    program = forms.ModelChoiceField(
        queryset=Program.objects.all(),
        empty_label="Selecione um programa",
        label="Programa",
        widget=forms.Select(attrs={"class": "form-control"}),
    )

    class Meta:
        model = User
        fields = [
            "username",
            "document",
            "registration_code",
            "course",
            "photo",
            "program",
        ]
        widgets = {
            "username": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Digite o nome do usuário",
                }
            ),
            "document": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Digite o CPF"}
            ),
            "registration_code": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Digite a matrícula"}
            ),
            "course": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Digite o curso"}
            ),
            "photo": forms.ClearableFileInput(
                attrs={
                    "class": "form-control",
                }
            ),
        }

    def clean_document(self):
        document = self.cleaned_data.get("document")

        if self.instance.pk:
            if (
                User.objects.exclude(pk=self.instance.pk)
                .filter(document=document)
                .exists()
                or Administrator.objects.filter(document=document).exists()
            ):
                raise ValidationError(
                    "Este CPF já está cadastrado em outro usuário ou administrador."
                )
        else:
            if (
                User.objects.filter(document=document).exists()
                or Administrator.objects.filter(document=document).exists()
            ):
                raise ValidationError(
                    "Este CPF já está cadastrado em outro usuário ou administrador."
                )
        return document

    def clean_registration_code(self):
        registration_code = self.cleaned_data.get("registration_code")

        if self.instance.pk:
            if (
                User.objects.exclude(pk=self.instance.pk)
                .filter(registration_code=registration_code)
                .exists()
                or Administrator.objects.filter(
                    registration_code=registration_code
                ).exists()
            ):
                raise ValidationError(
                    "Este código de matrícula já está cadastrado em outro usuário ou administrador."
                )
        else:
            if (
                User.objects.filter(registration_code=registration_code).exists()
                or Administrator.objects.filter(
                    registration_code=registration_code
                ).exists()
            ):
                raise ValidationError(
                    "Este código de matrícula já está cadastrado em outro usuário ou administrador."
                )
        return registration_code

apps/users/views.py
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
)
from django.urls import reverse_lazy
from .models import User
from .forms import UserForm
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from apps.logs.models import RecognitionLog
from datetime import datetime
import locale


class UserListView(ListView):
    model = User
    template_name = "user_list.html"
    context_object_name = "users"
    paginate_by = 10
    permission_required = "users.view_user"

    def get_queryset(self):
        queryset = super().get_queryset()
        name = self.request.GET.get("name")

        if name:
            queryset = queryset.filter(username__icontains=name)

        return queryset


class UserCreateView(CreateView):
    model = User
    template_name = "user_create.html"
    form_class = UserForm
    success_url = reverse_lazy("user_list")
    permission_required = "users.add_user"


class UserDetailView(DetailView):
    model = User
    template_name = "user_detail.html"
    permission_required = "users.view_user"
    # context_object_name = "user"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        recognition_logs = RecognitionLog.objects.filter(user_id=self.object)

        formatted_logs = []
        locale.setlocale(locale.LC_TIME, "pt_BR.UTF-8")

        for log in recognition_logs:
            formatted_logs.append(
                {
                    "data": log.access_time.date(),
                    "dia_semana": log.access_time.strftime("%A"),
                    "hora": log.access_time.strftime("%H:%M:%S"),
                    "status": log.status,
                }
            )

        context["recognition_logs"] = formatted_logs

        return context


class UserUpdateView(UpdateView):
    model = User
    template_name = "user_update.html"
    form_class = UserForm
    success_url = reverse_lazy("user_list")
    permission_required = "users.change_user"


class UserDeleteView(DeleteView):
    model = User
    template_name = "user_delete.html"
    success_url = reverse_lazy("user_list")
    permission_required = "users.delete_user"

apps/users/templates/user_create.html
{% extends "base.html" %}

{% block title %}
  Cadastro de Usuários
{% endblock %}

{% block content %}
<main>
  <div class="row mt-4">
    <div class="col-md-12">
      <div class="card text-center">
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" role="alert">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
        <div class="card-header">
          Cadastro de Usuários
        </div>
        <div class="card-body" style="text-align: left;">
          <p class="card-text">* Preencha os dados do usuário corretamente</p>
          <form method="post" enctype="multipart/form-data" action="{% url 'user_create' %}">
            {% csrf_token %}
            
            <div class="form-group mb-3">
              <label class="mb-1" for="id_username">Nome</label>
              {{ form.username }}
              {% if form.username.errors %}
                <div class="text-danger small">{{ form.username.errors|join:', ' }}</div>
              {% endif %}
            </div>
            
            <div class="form-group mb-3">
              <label class="mb-1" for="id_document">CPF</label>
              {{ form.document }}
              {% if form.document.errors %}
                <div class="text-danger small">{{ form.document.errors|join:', ' }}</div>
              {% endif %}
            </div>
            
            <div class="form-group mb-3">
              <label class="mb-1" for="id_registration_code">Matrícula</label>
              {{ form.registration_code }}
              {% if form.registration_code.errors %}
                <div class="text-danger small">{{ form.registration_code.errors|join:', ' }}</div>
              {% endif %}
            </div>
            
            <div class="form-group mb-3">
              <label class="mb-1" for="id_course">Curso</label>
              {{ form.course }}
              {% if form.course.errors %}
                <div class="text-danger small">{{ form.course.errors|join:', ' }}</div>
              {% endif %}
            </div>
            
            <div class="form-group mb-3">
              <label class="mb-1" for="id_program_id">Programa</label>
              {{ form.program }}
              {% if form.program.errors %}
                <div class="text-danger small">{{ form.program.errors|join:', ' }}</div>
              {% endif %}
            </div>
            
            <div class="form-group mb-3">
              <label class="mb-1" for="id_photo">Foto</label>
              {{ form.photo }}
              {% if form.photo.errors %}
                <div class="text-danger small">{{ form.photo.errors|join:', ' }}</div>
              {% endif %}
            </div>

            <button type="submit" class="btn btn-primary mt-3">Cadastrar</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

apps/users/templates/user_delete.html
{% extends 'base.html' %}

{% block title %}
  Deletar Usuário
{% endblock %}

{% block content %}
  <div class="container mt-4">
    <h3 class="display-5">Deletar Usuário</h3>

    <div class="card">
      <div class="card-body">
        <p class="card-text">Tem certeza de que deseja excluir o usuário <strong>{{ user.username }}</strong>?</p>

        <form method="post">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">Deletar</button>
        </form>
        
        <a href="{% url 'user_list' %}" class="btn btn-secondary mt-3">Cancelar</a>
      </div>
    </div>
  </div>
{% endblock %}

apps/users/templates/user_detail.html
{% extends 'base.html' %}

{% block title %}
  Reconhecimento Facial - Detalhes do Usuário
{% endblock %}

{% block content %}
<div class="container">
  <main>
    <div class="row">
      <div class="col-md-12">
        <div class="card text-center mt-3">
          <div class="card-header">
            Detalhes do Usuário
          </div>
          <div class="card-body" style="text-align: left;">
            <div class="row mt-3 info-usuario">
              <div class="col-md-3 container-image">
                <img id="foto-usuario" src="{{ user.photo.url|default:'img/semfoto.jpg' }}" alt="Foto do Usuário" width="100%">
              </div>
              <div class="col-md-8">
                <h4>Dados do Usuário</h4>
                <div class="detalhe-usuario"><strong>Nome: </strong>{{ user.username }}</div>
                <div><strong>CPF: </strong>{{ user.document }}</div>   
                <div><strong>Matrícula: </strong>{{ user.registration_code }}</div>
                <div><strong>Curso: </strong>{{ user.course }}</div>

                <div class="mt-2">
                  <button type="button" class="btn-cadastra-foto btn btn-primary" data-bs-toggle="modal" data-bs-target="#CadastrarFoto">
                    Cadastrar Foto
                  </button>
                </div>
                <a href="{% url 'user_list' %}" class="btn btn-secondary mt-3">Cancelar</a>
              </div>
            </div>
          </div>
        </div>

        <!-- Frequência do Usuário -->
        <div class="row mt-4">
          <div class="col-md-12">
            <div class="card text-center mt-3">
              <div class="card-header">
                Frequência do Usuário
              </div>
              <div class="listagem-usuarios">
                <table class="table table-hover" id="dados-frequencia">
                  <thead>
                    <tr>
                      <th scope="col">Data</th>
                      <th scope="col">Dia da semana</th>
                      <th scope="col">Hora</th>
                      <th scope="col">Status</th>
                    </tr>
                  </thead>
                  <tbody class="tbody">
                    {% for log in recognition_logs %}
                    <tr>
                      <td>{{ log.data }}</td>
                      <td>{{ log.dia_semana|capfirst }}</td>
                      <td>{{ log.hora }}</td>
                      <td>{{ log.status }}</td>
                    </tr>
                  {% empty %}
                    <tr>
                      <td colspan="4">Nenhuma frequência registrada.</td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </main>
</div>

<div class="modal fade" id="CadastrarFoto" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="CadastrarFotoLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="CadastrarFotoLabel">Cadastrar Foto do Usuário</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="post" action="#" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group">
            <label for="photo">Adicionar Foto:</label>
            <input type="file" class="form-control" name="photo" id="photo">
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
            <button type="submit" class="btn btn-primary">Salvar</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

apps/users/templates/user_list.html
{% extends "base.html" %}

{% block title %}
  Reconhecimento Facial - Usuários
{% endblock %}

{% block content %}
  <main>
    <div class="row mt-4">
      <div class="col-md-12">
        <div class="card text-center">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}" role="alert">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          <div class="card-header">
            Consulta de Usuários
          </div>
          <div class="card-body">
            <p class="card-text">* Listagem de usuários cadastrados.</p>
            <form method="get" action="{% url 'user_list' %}" class="mb-4">
              <div class="input-group">
                <input type="text" class="form-control" name="name" placeholder="Nome" value="{{ request.GET.name }}">
                <button class="btn btn-primary" type="submit"><i class="bi bi-search"></i></button>
              </div>
            </form>

            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Nome</th>
                  <th>CPF</th>
                  <th>Matrícula</th>
                  <th>Curso</th>
                  <th style="text-align: center;" colspan="2">Ações</th>
                </tr>
              </thead>
              <tbody>
                {% for user in users %}
                  <tr>
                    <td>{{ user.username }}</td>
                    <td>{{ user.document }}</td>
                    <td>{{ user.registration_code }}</td>
                    <td>{{ user.course }}</td>
                    <td>
                      <div class="d-flex gap-2 justify-content-center">
                        <a href="{% url 'user_detail' user.user_id %}" class="btn btn-info btn-sm">
                          <i class="bi bi-eye"></i>
                        </a>
                        <a href="{% url 'user_update' user.user_id %}" class="btn btn-warning btn-sm">
                          <i class="bi bi-pencil"></i>
                        </a>
                        <a href="{% url 'user_delete' user.user_id %}" class="btn btn-danger btn-sm">
                          <i class="bi bi-trash"></i>
                        </a>
                      </div>
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
            {% include 'components/_pagination.html' %}
          </div>
        </div>
      </div>
    </div>
  </main>
</div>
{% endblock %}

apps/users/templates/user_update.html
{% extends 'base.html' %}

{% block title %}
  Editar Usuário
{% endblock %}

{% block content %}
  <div class="container mt-4">
    <h3 class="display-5">Editar Usuário</h3>

    <div class="card">
      <div class="card-body">
        <form method="post" class="form">
          {% csrf_token %}
          
          <div class="form-group mb-3">
            <label for="{{ form.username.id_for_label }}">Nome de Usuário:</label>
            {{ form.username }}
          </div>

          <div class="form-group mb-3">
            <label for="{{ form.document.id_for_label }}">CPF:</label>
            {{ form.document }}
          </div>

          <div class="form-group mb-3">
            <label for="{{ form.course.id_for_label }}">Curso:</label>
            {{ form.course }}
          </div>

          <div class="form-group mb-3">
            <label for="{{ form.registration_code.id_for_label }}">Código de Matrícula:</label>
            {{ form.registration_code }}
          </div>

          <div class="form-group mb-3">
            <label for="{{ form.photo.id_for_label }}">Foto:</label>
            {{ form.photo }}
          </div>

          <button type="submit" class="btn btn-primary">Salvar</button>
        </form>
      </div>
    </div>

    <a href="{% url 'user_list' %}" class="btn btn-danger mt-3">Cancelar</a>
  </div>
{% endblock %}